name: Hackathon Evaluation

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate-q1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run Q1 Scoring
        run: python scripts/score_q1.py
